trigger:
  - master
 
 jobs:
  - job: Linux
  pool: 
    vmImage: 'ubuntu-16-04'
  steps: 
    - task: 'DotNetCoreInstaller@0'
      inputs: 
        packageType: 'sdk'
        version: '2.2.100'
    
     - script: 'dotnet clean'
       displayName: Server - Clean
